version: '3.9'

services:
  database:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - corbeau
    ports:
      - "3306:3306"
  server:
    image: corbeau
    container_name: corbeau
    ports:
      - "9000:9000"
    environment:
      mysql-host: 'mysql'
      mysql-port: '3306'
      server.port: '9000'
    depends_on:
      - database
    networks:
      - corbeau
networks:
  corbeau:
    driver: bridge
    external: false
