server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always
    include-headers: true
    include-cookies: true

spring:
  r2dbc:
    url: r2dbc:pool:mysql://${mysql-hostname:localhost}:${mysql-port:3306}/${mysql-table:db}
    username: ${mysql.username:user}
    password: ${mysql.password:password}
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      validation-query: SELECT 1
  redis:
    host: ${redis-hostname:localhost}
    port: ${redis-port:6379}
    timeout: 1H
  cache:
    type: redis
    redis:
      cache-null-values: true
  thymeleaf:
    reactive:
      max-chunk-size: 8192

logging:
  level:
    root: info


#remove data populator if not working of data
#It is because populator sql execution is increasing start up time.

#data:
#  populator: populator.sql
#  cleaner: cleaner.sql

moderation:
  prime:
    enable: true
    name: admin
    password: password
    role: prime
  roles: prime,writer,editor,support

image:
  rootDirectory: images
  removeIfExists: false
  repository:
    local:
      rootDirectory: images
  random:
    size: 8

name-surname-offer:
  pairs: Harry Potter,Severus Snape,Ron Weasley,Hermione Grange r,Draco Malfoy,Albus Dumbledore,Forrest Gump,Lord Voldemort,Sirius Black

validation:
  message:
    source:
      path: classpath:messages
      encoding: UTF-8