spring:
  r2dbc:
    url: r2dbc:pool:mysql://${mysql-hostname:localhost}:${mysql-port:3306}/${mysql-table:db}
    username: ${mysql.username:user}
    password: ${mysql.password:password}
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      validation-query: SELECT 1
  redis:
    host: ${redis-hostname:localhost}
    port: ${redis-port:6379}
    timeout: 1H
  cache:
    type: redis
    redis:
      cache-null-values: true
  thymeleaf:
    reactive:
      max-chunk-size: 8192

logging:
  level:
    root: info

#remove data populator if not working of data
#It is because populator sql execution is increasing start up time.

#data:
#  populator: populator.sql
#  cleaner: cleaner.sql
#
#image:
#  rootDirectory: images
#  removeIfExists: true
#
#moderation:
#  prime:
#    enable: true
#    name: admin
#    password: password
#    role: prime
#  roles: prime,writer,editor,support


###Use this properties if you are not working on data###

image:
  repository:
    local:
      rootDirectory: images
  random:
    size: 8

moderation:
  prime:
    enable: false
  roles:
    enabled: false

#########################################################

name-surname-offer:
  pairs: Harry Potter,Severus Snape,Ron Weasley,Hermione Granger,Draco Malfoy,Albus Dumbledore,Forrest Gump,Lord Voldemort,Sirius Black