server:
  address: 0.0.0.0
  port: 9000
  error:
    include-binding-errors: on_param
    include-exception: true
    include-message: on_param
    include-stacktrace: on_param
    include-headers: true
    include-cookies: true
    include-method: true
    include-excepiton-object: true

spring:
  r2dbc:
    url: r2dbc:pool:mysql://${mysql-hostname:localhost}:${mysql-port:3306}/${mysql-table:db}
    username: ${mysql.username:user}
    password: ${mysql.password:password}
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      validation-query: SELECT 1
  thymeleaf:
    reactive:
      max-chunk-size: 8192

logging:
  level:
    root: info

#remove data populator if not working of data
#It is because populator sql execution is increasing start up time.
#data:
#  populator: populator.sql
#  cleaner: cleaner.sql
#moderation:
#  prime:
#    enable: true
#    name: admin
#    password: password
#    role: prime
#  roles: prime,writer,editor,support

moderation:
  prime:
    enable: false
  roles:
    enabled: false

##############################

image:
  rootDirectory: images
  removeIfExists: false
  repository:
    local:
      rootDirectory: images
  random:
    size: 8
  path:
    notFound: src/main/resources/static/image/image-not-found.png

name-surname-offer:
  pairs: Harry Potter,Severus Snape,Ron Weasley,Hermione Grange r,Draco Malfoy,Albus Dumbledore,Forrest Gump,Lord Voldemort,Sirius Black

validation:
  message:
    source:
      path: classpath:messages
      encoding: UTF-8

app-status:
  comment:
    activated: true

hazelcast:
  trace:
    comment:
      map-name: comment-map
    login:
      map-name: login-map
